_base_ = ["reward-standard-base.py"]

# PT-v3m1 (paper-recommended widths/depths)
model = dict(
    backbone_out_channels=32,
    mlp_hidden=128,
    backbone=dict(
        type="PT-v3m1",
        in_channels=3,
        order=("z", "z-trans", "hilbert", "hilbert-trans"),
        stride=(2, 2, 2, 2),
        enc_depths=(2, 2, 2, 4, 2),
        enc_channels=(16, 32, 64, 128, 256),
        enc_num_head=(2, 2, 4, 8, 16),
        enc_patch_size=(256, 256, 256, 256, 256),
        dec_depths=(2, 2, 2, 1),
        dec_channels=(32, 32, 64, 128),
        dec_num_head=(4, 4, 8, 8),
        dec_patch_size=(256, 256, 256, 256),
        mlp_ratio=3,
        qkv_bias=True,
        qk_scale=None,
        attn_drop=0.1,
        proj_drop=0.1,
        drop_path=0.2,
        shuffle_orders=True,
        pre_norm=True,
        enable_rpe=False,
        enable_flash=False,
        upcast_attention=True,
        upcast_softmax=True,
        enc_mode=False,
        pdnorm_bn=False,
        pdnorm_ln=False,
        pdnorm_decouple=True,
        pdnorm_adaptive=False,
        pdnorm_affine=True,
        pdnorm_conditions=("ScanNet", "S3DIS", "Structured3D"),
    ),
)
